services:
  grafana-db-exporter:
    build:
      context: .
      dockerfile: ./docker/grafana-db-exporter/Dockerfile
    env_file:
      - .env
    volumes:
      # mount the ssh key to the container
      - ~/.ssh/id_rsa:/app/.ssh/id_rsa:ro
      # - ~/.ssh/id_ed25519:/app/.ssh/id_ed25519:ro
      # - ~/.ssh/id_ecdsa:/app/.ssh/id_ecdsa:ro
      - ~/.ssh/known_hosts:/app/.ssh/known_hosts:ro
    networks:
      - grafana-network
    depends_on:
      - grafana

  grafana:
    build:
      context: ./docker/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - grafana-network

volumes:
  grafana-storage:

networks:
  grafana-network:
    driver: bridge
